micronaut:
   application:
        name: schism-web
                
# Uncomment to set server port
   server:
       port: 8081

   security:
       enabled: false
               
datasources:
    default:
        # url: jdbc:h2:file:./db/schismdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        url: jdbc:h2:tcp://localhost:9092/schismdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false
        username: sa
        password: ""
        driverClassName: org.h2.Driver
